name: Frontend Deployment
on:
  push:
    branches:
      - team2-elisha

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run Frontend Deployment Script
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          chmod +x ./scripts/deploy-frontend.sh
          ./scripts/deploy-frontend.sh  

      - name: Run Cypress E2E Tests
        working-directory: ./frontend
        run: npx cypress run
        env:
          CYPRESS_BASE_URL: https://d2zorvncrj5h3f.cloudfront.net
          CYPRESS_API_URL: http://ec2-100-24-58-46.compute-1.amazonaws.com
